name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.0
      
    - name: Lowercase the repo name and username
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        file: ./ruoyi-admin/Dockerfile
        cache-from: type=gha
        tags: ${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Lowercase the repo name and username
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 47.106.181.192
        port: 22
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull ${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}
          docker rm -f ruoyi-api | true 
          docker run -d -p 6040:6039 --name ruoyi-api ${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}
